// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArOfDWWx8Uovr5pUz8_2O-C5NKoG4O_Js',
    appId: '1:421097076698:web:f1da788b565033076432e3',
    messagingSenderId: '421097076698',
    projectId: 'uborrow-184e9',
    authDomain: 'uborrow-184e9.firebaseapp.com',
    storageBucket: 'uborrow-184e9.firebasestorage.app',
    measurementId: 'G-JY4DJ66VD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wNJdZ-sG9Dlu75TFzYVQrr1FxT4ceQg',
    appId: '1:421097076698:android:51dcf8a0bc76f41c6432e3',
    messagingSenderId: '421097076698',
    projectId: 'uborrow-184e9',
    storageBucket: 'uborrow-184e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAshSrCMn1sdZalxLHnRb8W4NQdYmnNlc',
    appId: '1:421097076698:ios:c3e112b4d01f13366432e3',
    messagingSenderId: '421097076698',
    projectId: 'uborrow-184e9',
    storageBucket: 'uborrow-184e9.firebasestorage.app',
    iosBundleId: 'com.example.uborrow',
  );
}
